# .readthedocs.yml
# Read the Docs configuration file
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

python:
  install:
    - path: .  # Install your local package
    - requirements: docs/requirements.txt  # Install doc dependencies

sphinx:
  configuration: docs/source/conf.py
