name: Test and Publish to TestPyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip build
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  install-check:
    needs: release-build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install and check import
        shell: bash
        run: |
          python -m venv venv
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            venv\Scripts\activate.bat
            for %%F in (dist\*.whl) do python -m pip install --upgrade pip && python -m pip install "%%~F"
          else
            source venv/bin/activate
            python -m pip install --upgrade pip
            python -m pip install dist/*.whl
          fi
          python -c "import ciss_vae"

  testpypi-publish:
    needs: install-check
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/project/ciss-vae/
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
