name: TestPyPI CI/CD

on:
  release:
    types: [published]    # Runs only when a GitHub Release is created

permissions:
  contents: read

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Upload built distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/

  install-check:
    name: Install and test import on matrix
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: dist/
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Create venv & install
        shell: bash
        run: |
          python -m venv venv
          source venv/bin/activate || .\venv\Scripts\activate
          pip install --upgrade pip
          pip install dist/*.whl
          python -c "import ciss_vae"

  testpypi-publish:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: install-check
    environment:
      name: testpypi
      url: https://test.pypi.org/project/ciss-vae/
    permissions:
      id-token: write        # Needed for GitHub OIDC token
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: dist/
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
