name: Test and Publish to TestPyPI

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip build
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  install-check:
    runs-on: ${{ matrix.os }}
    needs: release-build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install and check import (unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install dist/*.whl
          python -c "import ciss_vae"

      - name: Install and check import (windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python -m venv venv
          venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install dist\*.whl
          python -c "import ciss_vae"

  testpypi-publish:
    runs-on: ubuntu-latest
    needs: install-check
    environment:
      name: testpypi
      url: https://test.pypi.org/project/ciss-vae/
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
