name: Test and Publish to TestPyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build distributions
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  install-check:
    runs-on: ${{ matrix.os }}
    needs: release-build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install and check import
        shell: bash
        run: |
          python -m venv venv
          source venv/bin/activate || .\venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install dist/*.whl
          python -c "import ciss_vae"  # ensure main package imports correctly

  testpypi-publish:
    runs-on: ubuntu-latest
    needs: install-check
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/project/ciss-vae/
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
