name: Test and Publish to TestPyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build distributions
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  install-check:
    runs-on: ${{ matrix.os }}
    needs: release-build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install and check import
        shell: bash
        run: |
          python -m venv venv
          python -m pip install --upgrade pip
          . venv/bin/activate
          pip install dist/*.whl
          python -c "import ciss_vae"
          
  testpypi-publish:
    runs-on: ubuntu-latest
    needs: install-check
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/project/ciss-vae/
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
