# name: Upload Python Package

# on:
#   release:
#     types: [published]

# permissions:
#   contents: read

# jobs:
#   release-build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.x"

#       - name: Build release distributions
#         run: |
#           python -m pip install --upgrade pip
#           python -m pip install build
#           python -m build

#       - name: Upload distributions
#         uses: actions/upload-artifact@v4
#         with:
#           name: release-dists
#           path: dist/

#   install-check:
#     runs-on: ${{ matrix.os }}
#     needs: release-build
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest, windows-latest]

#     steps:
#       - name: Download build artifacts
#         uses: actions/download-artifact@v4
#         with:
#           name: release-dists
#           path: dist/

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.x"

#       - name: Install wheel and test import
#         run: |
#           python -m venv venv
#           source venv/bin/activate || .\venv\Scripts\activate
#           python -m pip install --upgrade pip
#           pip install dist/*.whl
#           python -c "import ciss-vae"  # ← replace with actual package name

#   pypi-publish:
#     runs-on: ubuntu-latest
#     needs:
#       - release-build
#       - install-check
#     permissions:
#       id-token: write

#     environment:
#       name: pypi
#       url: https://pypi.org/project/ciss_vae/ 
#     steps:
#       - name: Retrieve release distributions
#         uses: actions/download-artifact@v4
#         with:
#           name: release-dists
#           path: dist/

#       - name: Publish release distributions to PyPI
#         uses: pypa/gh-action-pypi-publish@release/v1
#         with:
#           packages-dir: dist/
