name: Test & Publish to TestPyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: 🛠 Build distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python -m pip install --upgrade pip build
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  install-check:
    name: ✅ Install & import check
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install and check import
        shell: bash
        run: |
          python -m venv venv
          python -m pip install --upgrade pip
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            call venv\Scripts\activate.bat
          else
            . venv/bin/activate
          fi
          pip install dist/*.whl
          python -c "import ciss_vae"
          
  testpypi-publish:
    name: 🚀 Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: install-check
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/project/ciss-vae/
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
